<a href="https://colab.research.google.com/github/Firebreather-heart/firebc-hamoye/blob/main/stagec_hamoye.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 **importing libraries**

In [2]:
import pandas as pd
import numpy as np

**Reading dataset**

In [4]:
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/00471/Data_for_UCI_named.csv')

In [5]:
df

,tau1,tau2,tau3,tau4,p1,p2,p3,p4,g1,g2,g3,g4,stab,stabf
0,2.959060,3.079885,8.381025,9.780754,3.763085,-0.782604,-1.257395,-1.723086,0.650456,0.859578,0.887445,0.958034,0.055347,unstable
1,9.304097,4.902524,3.047541,1.369357,5.067812,-1.940058,-1.872742,-1.255012,0.413441,0.862414,0.562139,0.781760,-0.005957,stable
2,8.971707,8.848428,3.046479,1.214518,3.405158,-1.207456,-1.277210,-0.920492,0.163041,0.766689,0.839444,0.109853,0.003471,unstable
3,0.716415,7.669600,4.486641,2.340563,3.963791,-1.027473,-1.938944,-0.997374,0.446209,0.976744,0.929381,0.362718,0.028871,unstable
4,3.134112,7.608772,4.943759,9.857573,3.525811,-1.125531,-1.845975,-0.554305,0.797110,0.455450,0.656947,0.820923,0.049860,unstable
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2.930406,9.487627,2.376523,6.187797,3.343416,-0.658054,-1.449106,-1.236256,0.601709,0.779642,0.813512,0.608385,0.023892,unstable
9996,3.392299,1.274827,2.954947,6.894759,4.349512,-1.663661,-0.952437,-1.733414,0.502079,0.567242,0.285880,0.366120,-0.025803,stable
9997,2.364034,2.842030,8.776391,1.008906,4.299976,-1.380719,-0.943884,-1.975373,0.487838,0.986505,0.149286,0.145984,-0.031810,stable
9998,9.631511,3.994398,2.757071,7.821347,2.514755,-0.966330,-0.649915,-0.898510,0.365246,0.587558,0.889118,0.818391,0.037789,unstable
9999,6.530527,6.781790,4.349695,8.673138,3.492807,-1.390285,-1.532193,-0.570329,0.073056,0.505441,0.378761,0.942631,0.045263,unstable

**Dataset exploration**

In [6]:
df.isnull().sum()

tau1     0
tau2     0
tau3     0
tau4     0
p1       0
p2       0
p3       0
p4       0
g1       0
g2       0
g3       0
g4       0
stab     0
stabf    0
dtype: int64

In [7]:
df.describe()

,tau1,tau2,tau3,tau4,p1,p2,p3,p4,g1,g2,g3,g4,stab
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,5.250000,5.250001,5.250004,5.249997,3.750000,-1.250000,-1.250000,-1.250000,0.525000,0.525000,0.525000,0.525000,0.015731
std,2.742548,2.742549,2.742549,2.742556,0.752160,0.433035,0.433035,0.433035,0.274256,0.274255,0.274255,0.274255,0.036919
min,0.500793,0.500141,0.500788,0.500473,1.582590,-1.999891,-1.999945,-1.999926,0.050009,0.050053,0.050054,0.050028,-0.080760
25%,2.874892,2.875140,2.875522,2.874950,3.218300,-1.624901,-1.625025,-1.624960,0.287521,0.287552,0.287514,0.287494,-0.015557
50%,5.250004,5.249981,5.249979,5.249734,3.751025,-1.249966,-1.249974,-1.250007,0.525009,0.525003,0.525015,0.525002,0.017142
75%,7.624690,7.624893,7.624948,7.624838,4.282420,-0.874977,-0.875043,-0.875065,0.762435,0.762490,0.762440,0.762433,0.044878
max,9.999469,9.999837,9.999450,9.999443,5.864418,-0.500108,-0.500072,-0.500025,0.999937,0.999944,0.999982,0.999930,0.109403

In [10]:
df.pop('stab')

0       0.055347
1      -0.005957
2       0.003471
3       0.028871
4       0.049860
          ...
9995    0.023892
9996   -0.025803
9997   -0.031810
9998    0.037789
9999    0.045263
Name: stab, Length: 10000, dtype: float64

In [19]:
y = df.pop('stabf')
x = df

In [21]:
from sklearn.preprocessing import StandardScaler,LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier

In [32]:
le = LabelEncoder()
y = le.fit_transform(y)

In [33]:
x_train, x_val, y_train,y_val = train_test_split(x,y, random_state=1, test_size=0.2)

In [34]:
scl = StandardScaler()
scaled_t = scl.fit_transform(x_train)
scl_v = scl.fit_transform(x_val)

In [35]:
x_train = pd.DataFrame(scaled_t, columns = x.columns)
x_val = pd.DataFrame(scl_v, columns = x.columns)

In [38]:
y_train

array([1, 1, 1, ..., 1, 1, 0])

In [44]:
def trainmodel(model,  train_x, train_y,random_state=1,):
    mod = model(random_state = random_state)
    mod.fit(train_x,train_y)
    return mod
from sklearn.metrics import classification_report
def evalmodel(model, val_x,val_y):
    pred = model.predict(val_x)
    print(model, '\n', classification_report(pred, val_y))

class Dataflow:
    def __init__(self, trainx,trainy, valx,valy):
        self.models = [RandomForestClassifier, ExtraTreesClassifier, XGBClassifier, LGBMClassifier]
        self.x_t = trainx
        self.x_v = valx 
        self.y_t = trainy 
        self.y_v = valy
    
    def rollover(self):
        self.trained_models = []
        for model in self.models:
            self.trained_models.append(trainmodel(model, self.x_t, self.y_t))
        for model in self.trained_models:
            evalmodel(model, self.x_v, self.y_v)

In [45]:
db = Dataflow(x_train, y_train, x_val, y_val)

In [46]:
db.rollover()

RandomForestClassifier(random_state=1)
               precision    recall  f1-score   support

           0       0.88      0.92      0.90       680
           1       0.96      0.93      0.94      1320

    accuracy                           0.93      2000
   macro avg       0.92      0.93      0.92      2000
weighted avg       0.93      0.93      0.93      2000

ExtraTreesClassifier(random_state=1)
               precision    recall  f1-score   support

           0       0.85      0.94      0.89       640
           1       0.97      0.92      0.94      1360

    accuracy                           0.93      2000
   macro avg       0.91      0.93      0.92      2000
weighted avg       0.93      0.93      0.93      2000

XGBClassifier(random_state=1)
               precision    recall  f1-score   support

           0       0.84      0.92      0.88       648
           1       0.96      0.92      0.94      1352

    accuracy                           0.92      2000
   macro avg       0.90      0.92      0.91      2000
weighted avg       0.92      0.92      0.92      2000

LGBMClassifier(random_state=1)
               precision    recall  f1-score   support

           0       0.89      0.92      0.91       687
           1       0.96      0.94      0.95      1313

    accuracy                           0.94      2000
   macro avg       0.93      0.93      0.93      2000
weighted avg       0.94      0.94      0.94      2000